# Docker Compose settings for launching PostgreSQL and Redis databases
# You can override these settings in docker-compose.override.yml
# https://docs.docker.com/compose/compose-file/

version: '3'

volumes:
  ? db

services:
  # SQL and document data store
  db:
    image: db
    build:
      context: ./images/db
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - '127.0.0.1:5432:5432'
